### ISSUE TITLE
MIT 单变量微积分 03 求导四则运算及三角函数导数

### ISSUE THREAD

**Issue by alexwanng** [alexwanng/alexcode#35]
* [多项式导数](#-----)
    + [常数的导数是0](#------0)
    + [x^n 的导数](#x-n----)
    + [cu的导数](#cu---)
    + [u + v 导数](#u---v---)
    + [u * v 导数](#u---v---)
    + [u / v 导数](#u---v---)
  * [sinx cosx的导数](#sinx-cosx---)
    + [sinx 导数](#sinx---)
    + [补充： sinx/x = 1 证明：](#----sinx-x---1----)
    + [补充(cosx - 1)/x = 0证明:  方法一， 依赖 sinx/x](#---cosx---1--x---0-------------sinx-x)
    + [补充(cosx - 1)/x = 0证明: (洛必达法则) 方法二](#---cosx---1--x---0---------------)
    + [cosx导数](#cosx--)

# Derivatives of Products, Quotients, Sine, and Cosine 

### 常数的导数是0
![image](https://user-images.githubusercontent.com/150418/33662280-2e321e56-dac6-11e7-98a8-586166cd430d.png)

> The geometric meaning this is that a horizontal straight line y=f(x) = c  has zero slope

### x^n 的导数
![image](https://user-images.githubusercontent.com/150418/33662866-7ae1c4fc-dac8-11e7-8bbe-826dc5d1503a.png)

> 注： 二项式定理:
![image](https://user-images.githubusercontent.com/150418/33662582-3846904c-dac7-11e7-89bd-909d9913be89.png)

> 注： 组合公式
![image](https://user-images.githubusercontent.com/150418/33662676-ae6f8d32-dac7-11e7-96c2-015d2e5954b6.png)

### cu的导数
![image](https://user-images.githubusercontent.com/150418/33663096-85076210-dac9-11e7-8fdb-d77a0fe31fc2.png)

> 上面啰嗦， 换一个:
![image](https://user-images.githubusercontent.com/150418/33664758-b1b1efbe-dacf-11e7-87b7-7d64c91107e6.png)

### u + v 导数
![image](https://user-images.githubusercontent.com/150418/33663731-1edebd3c-dacc-11e7-98ef-d6e35e41b018.png)

> 上面的啰嗦了， 换一个：
![image](https://user-images.githubusercontent.com/150418/33664625-3f6b466c-dacf-11e7-9ef5-969e06f09463.png)

### u * v 导数
![image](https://user-images.githubusercontent.com/150418/33664414-85004ef8-dace-11e7-829f-ee9e063d3108.png)

### u / v 导数
![image](https://user-images.githubusercontent.com/150418/33665618-85620e14-dad2-11e7-9081-dee38e109afc.png)

### sinx 导数
![image](https://user-images.githubusercontent.com/150418/33666814-129272bc-dad6-11e7-8f04-f9ddea144993.png)

### 补充： sinx/x = 1 证明：
![image](https://user-images.githubusercontent.com/150418/33694037-e86839c6-db30-11e7-89e4-9d3da5617ebc.png)

### 补充(cosx - 1)/x = 0证明:  方法一， 依赖 sinx/x
![image](https://user-images.githubusercontent.com/150418/33755879-d4f75c5c-dc2d-11e7-9554-2fd98c666734.png)

### 补充(cosx - 1)/x = 0证明: (洛必达法则) 方法二
![image](https://user-images.githubusercontent.com/150418/33694859-65eeb8e4-db35-11e7-9b8d-3073398926f0.png)

### cosx导数
![image](https://user-images.githubusercontent.com/150418/33667135-fbaa2350-dad6-11e7-95a8-feff20588740.png)

**Comment by foxlog** [comment]
# Derivatives of Products, Quotients, Sine, and Cosine 

## 多项式导数
### 常数的导数是0

### x^n 的导数

### cu的导数

### u + v 导数

### u * v 导数

### u / v 导数



## sinx cosx的导数
